# src/auth/auth.graphql
type User {
  id: ID!
  name: String!
  email: String!
  role: String!
}

input RegisterInput {
  name: String!
  email: String!
  password: String!
  role: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
}
