steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # assumes your package.json has "build" script like "ng build --prod"

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'frontend',
        '--region=europe-west1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--image=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
      ]

images:
  - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'

timeout: '1200s'
