# cloudbuild.yaml

steps:
  # Installer les dépendances
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Construire le projet (adapter selon le repo)
  # Pour frontend Angular, remplacer par 'npm run build'
  # Pour backend NestJS, souvent 'npm run build' suffit
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Déployer sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--region=${_REGION}',
        '--platform=managed',
        '--allow-unauthenticated',
        '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      ]

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'

# Timeout max (20 minutes)
timeout: '1200s'

# Variables substituables
substitutions:
  _SERVICE_NAME: 'nom-du-service'  # ex: frontend, auth-service, product-service
  _REGION: 'europe-west1'           # adapte selon ta région
