services:
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "4001:4001"
    # ... other config

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "4002:4002"
    # ... other config

  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "4003:4003"
    # ... other config

  gateway:
    build: ./backend/gateway
    container_name: gateway
    ports:
      - "3000:3000"
    # ... other config

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - gateway
