

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo
      - auth-service
      - kafka
    environment:
      - DATABASE_NAME=agroconnect-products
      - MONGO_URL=mongodb://mongo:27017/agroconnect-products

  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "4003:4003"
    depends_on:
      - mongo
      - auth-service
      - product-service
      - kafka
    environment:
      - DATABASE_NAME=agroconnect
      - MONGO_URL=mongodb://mongo:27017/agroconnect

volumes:
  mongo-data:
