type Order {
  id: ID!
  productId: ID!
  quantity: Int!
  total: Float!
}

type Query {
  orders: [Order]
  order(id: ID!): Order
}

type Mutation {
  createOrder(productId: ID!, quantity: Int!, total: Float!): Order
  updateOrder(id: ID!, quantity: Int, total: Float): Order
  deleteOrder(id: ID!): String
}
